/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion.Sistema;

import jssc.SerialPortList;
import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import jssc.SerialPort;

/**
 *
 * @author Juan Luis Diaz Aylas
 */
public class FrmPortCom extends javax.swing.JInternalFrame {

    SerialPortList puertoserial;

    /**
     * Creates new form FrmPortCom
     */
    public FrmPortCom() {
        initComponents();
        DesactivarOpcionesBalanzaG();
        DesactivarOpcionesBalanzaC();
        //habilitarpuerto();
        //    buscarPuertos();
    }

    private void buscarPuertos() {
        try {
            if (chkBalanzaGrande.isSelected()) {
                cbBalanzaGrande.removeAllItems();
            } else if (chkBalanzaChica.isSelected()) {
                cbBalanzaChica.removeAllItems();
            }
            Object[] puertos = SerialPortList.getPortNames();
            for (Object puerto : puertos) {
                cbBalanzaGrande.addItem((String) puerto);
                cbBalanzaChica.addItem((String) puerto);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void DesactivarOpcionesBalanzaC() {
        cbBalanzaChica.setEnabled(false);
        cbBaudiosC.setEnabled(false);
        cbDatosC.setEnabled(false);
        cbParadaC.setEnabled(false);
        cbParidadC.setEnabled(false);
        cbBalanzaChica.setSelectedIndex(-1);
        cbBaudiosC.setSelectedIndex(-1);
        cbDatosC.setSelectedIndex(-1);
        cbParadaC.setSelectedIndex(-1);
        cbParidadC.setSelectedIndex(-1);
    }

    private void DesactivarOpcionesBalanzaG() {
        cbBalanzaGrande.setEnabled(false);
        cbBaudiosG.setEnabled(false);
        cbDatosG.setEnabled(false);
        cbParadaG.setEnabled(false);
        cbParidadG.setEnabled(false);
        cbBalanzaGrande.setSelectedIndex(-1);
        cbBaudiosG.setSelectedIndex(-1);
        cbDatosG.setSelectedIndex(-1);
        cbParadaG.setSelectedIndex(-1);
        cbParidadG.setSelectedIndex(-1);
    }

    private void ActivarOpcionesBalanzaC() {
        cbBalanzaChica.setEnabled(true);
        cbBaudiosC.setEnabled(true);
        cbDatosC.setEnabled(true);
        cbParadaC.setEnabled(true);
        cbParidadC.setEnabled(true);
        cbBalanzaChica.setSelectedIndex(0);
    }

    private void ActivarOpcionesBalanzaG() {
        cbBalanzaGrande.setEnabled(true);
        cbBaudiosG.setEnabled(true);
        cbDatosG.setEnabled(true);
        cbParadaG.setEnabled(true);
        cbParidadG.setEnabled(true);
        cbBalanzaGrande.setSelectedIndex(0);
    }

    private void habilitarpuertoG() {
        try {
            if (chkBalanzaGrande.isSelected()) {
            ActivarOpcionesBalanzaG();
            jpanel.updateUI();
        } else {
            DesactivarOpcionesBalanzaG();
            jpanel.updateUI();
        }
        } catch (Exception e) {
        }
        
    }

    private void habilitarpuertoC() {
        try {
            if (chkBalanzaChica.isSelected()) {
            ActivarOpcionesBalanzaC();
            jpanel.updateUI();
        } else {
            DesactivarOpcionesBalanzaC();
            jpanel.updateUI();
        }
        } catch (Exception e) {
        }
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbBalanzaGrande = new javax.swing.JComboBox<>();
        cbBalanzaChica = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbBaudiosG = new javax.swing.JComboBox<>();
        cbParidadG = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbDatosG = new javax.swing.JComboBox<>();
        cbParadaG = new javax.swing.JComboBox<>();
        chkBalanzaGrande = new javax.swing.JCheckBox();
        chkBalanzaChica = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        cbBaudiosC = new javax.swing.JComboBox<>();
        cbParidadC = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbDatosC = new javax.swing.JComboBox<>();
        cbParadaC = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configurar Puerto COM");

        jpanel.setBackground(new java.awt.Color(51, 204, 0));
        jpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jpanel.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 447, -1, -1));

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jpanel.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 447, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 3, 16)); // NOI18N
        jLabel1.setText("<html>Esta Ventana permite configurar los Puertos Serie de su sistema, Proceda con precaucion, podría dejar el sistema inutilizable</html>");
        jpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 0, 176, 143));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("BALANZA GRANDE");
        jpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 157, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("BALANZA CHICA");
        jpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 287, -1, -1));

        cbBalanzaGrande.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cbBalanzaGrande.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cbBalanzaGrandePopupMenuWillBecomeVisible(evt);
            }
        });
        jpanel.add(cbBalanzaGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 154, 113, -1));

        cbBalanzaChica.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jpanel.add(cbBalanzaChica, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 284, 113, -1));

        jLabel4.setText("Baudios");
        jpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel5.setText("Paridad");
        jpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 238, -1, -1));

        cbBaudiosG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "110", "300", "600", "1200", "4800", "9600", "14400", "19200", "38400", "57600", "115200", "128000", "256000" }));
        cbBaudiosG.setSelectedIndex(-1);
        jpanel.add(cbBaudiosG, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 197, 72, -1));

        cbParidadG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NINGUNA", "IMPAR", "PAR", "MARCA", "ESPACIO" }));
        cbParidadG.setSelectedIndex(-1);
        jpanel.add(cbParidadG, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 235, -1, -1));

        jLabel6.setText("Bit de Datos");
        jpanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 200, -1, -1));

        jLabel7.setText("Bit de Parada");
        jpanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 238, -1, -1));

        cbDatosG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "6", "7", "8" }));
        cbDatosG.setSelectedIndex(-1);
        jpanel.add(cbDatosG, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 197, 42, -1));

        cbParadaG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "1.5" }));
        cbParadaG.setSelectedIndex(-1);
        jpanel.add(cbParadaG, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 235, -1, -1));

        chkBalanzaGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBalanzaGrandeActionPerformed(evt);
            }
        });
        jpanel.add(chkBalanzaGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 154, -1, -1));

        chkBalanzaChica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBalanzaChicaActionPerformed(evt);
            }
        });
        jpanel.add(chkBalanzaChica, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 284, -1, -1));

        jLabel8.setText("Paridad");
        jpanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 371, -1, -1));

        cbBaudiosC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "110", "300", "600", "1200", "4800", "9600", "14400", "19200", "38400", "57600", "115200", "128000", "256000" }));
        cbBaudiosC.setSelectedIndex(-1);
        jpanel.add(cbBaudiosC, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 72, -1));

        cbParidadC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NINGUNA", "IMPAR", "PAR", "MARCA", "ESPACIO" }));
        cbParidadC.setSelectedIndex(-1);
        jpanel.add(cbParidadC, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 368, -1, -1));

        jLabel9.setText("Bit de Datos");
        jpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 336, -1, -1));

        jLabel10.setText("Bit de Parada");
        jpanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 368, -1, -1));

        cbDatosC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "6", "7", "8" }));
        cbDatosC.setSelectedIndex(-1);
        jpanel.add(cbDatosC, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 330, 42, -1));

        cbParadaC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "1.5" }));
        cbParadaC.setSelectedIndex(-1);
        jpanel.add(cbParadaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 368, -1, -1));

        jLabel11.setText("Baudios");
        jpanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 333, -1, -1));

        jLabel12.setText("Los cambios surtiran efecto, luego reiniciar la aplicacion. Cierre el Sistema y vuelva a ingresar");
        jpanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 399, 338, 30));

        btnActualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnActualizar.setText("Actualizar");
        jpanel.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 447, -1, -1));

        btnOpen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOpen.setText("Open");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });
        jpanel.add(btnOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 481, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void chkBalanzaGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBalanzaGrandeActionPerformed
        habilitarpuertoG();
    }//GEN-LAST:event_chkBalanzaGrandeActionPerformed

    private void chkBalanzaChicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBalanzaChicaActionPerformed
        habilitarpuertoC();        // TODO add your handling code here:
    }//GEN-LAST:event_chkBalanzaChicaActionPerformed

    private void cbBalanzaGrandePopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbBalanzaGrandePopupMenuWillBecomeVisible
        buscarPuertos();        // TODO add your handling code here:
    }//GEN-LAST:event_cbBalanzaGrandePopupMenuWillBecomeVisible

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        // TODO add your handling code here:
        try {
            Object[] puertos = SerialPortList.getPortNames();

//            puertoserial = (SerialPortList) puertos[cbBalanzaGrande.getSelectedIndex()];
//            puertoserial.setBa
            SerialPort[] sp = new SerialPort[cbBalanzaGrande.getSelectedIndex()];

        } catch (Exception e) {
        }


    }//GEN-LAST:event_btnOpenActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPortCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPortCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPortCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPortCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPortCom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbBalanzaChica;
    private javax.swing.JComboBox<String> cbBalanzaGrande;
    private javax.swing.JComboBox<String> cbBaudiosC;
    private javax.swing.JComboBox<String> cbBaudiosG;
    private javax.swing.JComboBox<String> cbDatosC;
    private javax.swing.JComboBox<String> cbDatosG;
    private javax.swing.JComboBox<String> cbParadaC;
    private javax.swing.JComboBox<String> cbParadaG;
    private javax.swing.JComboBox<String> cbParidadC;
    private javax.swing.JComboBox<String> cbParidadG;
    private javax.swing.JCheckBox chkBalanzaChica;
    private javax.swing.JCheckBox chkBalanzaGrande;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jpanel;
    // End of variables declaration//GEN-END:variables
}
