/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion.Sistema;

import jssc.SerialPortList;
import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import jssc.SerialPort;

/**
 *
 * @author Juan Luis Diaz Aylas
 */
public class FrmPortCom extends javax.swing.JFrame {

    SerialPortList puertoserial;

    /**
     * Creates new form FrmPortCom
     */
    public FrmPortCom() {
        initComponents();
        DesactivarOpcionesBalanzaG();
        DesactivarOpcionesBalanzaC();
        //habilitarpuerto();
        //    buscarPuertos();
    }

    private void buscarPuertos() {
        try {
            if (chkBalanzaGrande.isSelected()) {
                cbBalanzaGrande.removeAllItems();
            } else if (chkBalanzaChica.isSelected()) {
                cbBalanzaChica.removeAllItems();
            }
            Object[] puertos = SerialPortList.getPortNames();
            for (Object puerto : puertos) {
                cbBalanzaGrande.addItem((String) puerto);
                cbBalanzaChica.addItem((String) puerto);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void DesactivarOpcionesBalanzaC() {
        cbBalanzaChica.setEnabled(false);
        cbBaudiosC.setEnabled(false);
        cbDatosC.setEnabled(false);
        cbParadaC.setEnabled(false);
        cbParidadC.setEnabled(false);
        cbBalanzaChica.setSelectedIndex(-1);
        cbBaudiosC.setSelectedIndex(-1);
        cbDatosC.setSelectedIndex(-1);
        cbParadaC.setSelectedIndex(-1);
        cbParidadC.setSelectedIndex(-1);
    }

    private void DesactivarOpcionesBalanzaG() {
        cbBalanzaGrande.setEnabled(false);
        cbBaudiosG.setEnabled(false);
        cbDatosG.setEnabled(false);
        cbParadaG.setEnabled(false);
        cbParidadG.setEnabled(false);
        cbBalanzaGrande.setSelectedIndex(-1);
        cbBaudiosG.setSelectedIndex(-1);
        cbDatosG.setSelectedIndex(-1);
        cbParadaG.setSelectedIndex(-1);
        cbParidadG.setSelectedIndex(-1);
    }

    private void ActivarOpcionesBalanzaC() {
        cbBalanzaChica.setEnabled(true);
        cbBaudiosC.setEnabled(true);
        cbDatosC.setEnabled(true);
        cbParadaC.setEnabled(true);
        cbParidadC.setEnabled(true);
        cbBalanzaChica.setSelectedIndex(0);
    }

    private void ActivarOpcionesBalanzaG() {
        cbBalanzaGrande.setEnabled(true);
        cbBaudiosG.setEnabled(true);
        cbDatosG.setEnabled(true);
        cbParadaG.setEnabled(true);
        cbParidadG.setEnabled(true);
        cbBalanzaGrande.setSelectedIndex(0);
    }

    private void habilitarpuertoG() {
        if (chkBalanzaGrande.isSelected()) {
            ActivarOpcionesBalanzaG();
            jpanel.updateUI();
        } else {
            DesactivarOpcionesBalanzaG();
            jpanel.updateUI();
        }
    }

    private void habilitarpuertoC() {
        if (chkBalanzaChica.isSelected()) {
            ActivarOpcionesBalanzaC();
            jpanel.updateUI();
        } else {
            DesactivarOpcionesBalanzaC();
            jpanel.updateUI();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbBalanzaGrande = new javax.swing.JComboBox<>();
        cbBalanzaChica = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbBaudiosG = new javax.swing.JComboBox<>();
        cbParidadG = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbDatosG = new javax.swing.JComboBox<>();
        cbParadaG = new javax.swing.JComboBox<>();
        chkBalanzaGrande = new javax.swing.JCheckBox();
        chkBalanzaChica = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        cbBaudiosC = new javax.swing.JComboBox<>();
        cbParidadC = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbDatosC = new javax.swing.JComboBox<>();
        cbParadaC = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configurar Puerto COM");

        jpanel.setBackground(new java.awt.Color(51, 204, 0));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 3, 16)); // NOI18N
        jLabel1.setText("<html>Esta Ventana permite configurar los Puertos Serie de su sistema, Proceda con precaucion, podría dejar el sistema inutilizable</html>");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("BALANZA GRANDE");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("BALANZA CHICA");

        cbBalanzaGrande.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cbBalanzaGrande.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cbBalanzaGrandePopupMenuWillBecomeVisible(evt);
            }
        });

        cbBalanzaChica.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel4.setText("Baudios");

        jLabel5.setText("Paridad");

        cbBaudiosG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "110", "300", "600", "1200", "4800", "9600", "14400", "19200", "38400", "57600", "115200", "128000", "256000" }));
        cbBaudiosG.setSelectedIndex(-1);

        cbParidadG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NINGUNA", "IMPAR", "PAR", "MARCA", "ESPACIO" }));
        cbParidadG.setSelectedIndex(-1);

        jLabel6.setText("Bit de Datos");

        jLabel7.setText("Bit de Parada");

        cbDatosG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "6", "7", "8" }));
        cbDatosG.setSelectedIndex(-1);

        cbParadaG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "1.5" }));
        cbParadaG.setSelectedIndex(-1);

        chkBalanzaGrande.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkBalanzaGrandeItemStateChanged(evt);
            }
        });
        chkBalanzaGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBalanzaGrandeActionPerformed(evt);
            }
        });

        chkBalanzaChica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBalanzaChicaActionPerformed(evt);
            }
        });

        jLabel8.setText("Paridad");

        cbBaudiosC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "110", "300", "600", "1200", "4800", "9600", "14400", "19200", "38400", "57600", "115200", "128000", "256000" }));
        cbBaudiosC.setSelectedIndex(-1);

        cbParidadC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NINGUNA", "IMPAR", "PAR", "MARCA", "ESPACIO" }));
        cbParidadC.setSelectedIndex(-1);

        jLabel9.setText("Bit de Datos");

        jLabel10.setText("Bit de Parada");

        cbDatosC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "6", "7", "8" }));
        cbDatosC.setSelectedIndex(-1);

        cbParadaC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "1.5" }));
        cbParadaC.setSelectedIndex(-1);

        jLabel11.setText("Baudios");

        jLabel12.setText("Los cambios surtiran efecto, luego reiniciar la aplicacion. Cierre el Sistema y vuelva a ingresar");

        btnActualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnActualizar.setText("Actualizar");

        btnOpen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOpen.setText("Open");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelLayout = new javax.swing.GroupLayout(jpanel);
        jpanel.setLayout(jpanelLayout);
        jpanelLayout.setHorizontalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelLayout.createSequentialGroup()
                        .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(jpanelLayout.createSequentialGroup()
                                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanelLayout.createSequentialGroup()
                                        .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbParidadG, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbBaudiosG, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jpanelLayout.createSequentialGroup()
                                        .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbBaudiosC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbParidadC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jpanelLayout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1))
                                    .addGroup(jpanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanelLayout.createSequentialGroup()
                                                .addComponent(cbBalanzaChica, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(chkBalanzaChica))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanelLayout.createSequentialGroup()
                                                .addComponent(cbBalanzaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(32, 32, 32)
                                                .addComponent(chkBalanzaGrande))
                                            .addGroup(jpanelLayout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel10))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cbParadaC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(cbDatosC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(jpanelLayout.createSequentialGroup()
                                                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel7))
                                                .addGap(32, 32, 32)
                                                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cbParadaG, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(cbDatosG, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLayout.createSequentialGroup()
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOpen)
                            .addGroup(jpanelLayout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(61, 61, 61)
                                .addComponent(btnSalir)))
                        .addGap(49, 49, 49))))
        );
        jpanelLayout.setVerticalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkBalanzaGrande)
                    .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cbBalanzaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbBaudiosG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbDatosG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbParidadG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbParadaG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkBalanzaChica, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(cbBalanzaChica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelLayout.createSequentialGroup()
                        .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(cbBaudiosC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)
                        .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(cbParidadC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbDatosC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbParadaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOpen)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void chkBalanzaGrandeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkBalanzaGrandeItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBalanzaGrandeItemStateChanged

    private void chkBalanzaGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBalanzaGrandeActionPerformed
        habilitarpuertoG();
    }//GEN-LAST:event_chkBalanzaGrandeActionPerformed

    private void chkBalanzaChicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBalanzaChicaActionPerformed
        habilitarpuertoC();        // TODO add your handling code here:
    }//GEN-LAST:event_chkBalanzaChicaActionPerformed

    private void cbBalanzaGrandePopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbBalanzaGrandePopupMenuWillBecomeVisible
        buscarPuertos();        // TODO add your handling code here:
    }//GEN-LAST:event_cbBalanzaGrandePopupMenuWillBecomeVisible

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        // TODO add your handling code here:
        try {
            Object[] puertos = SerialPortList.getPortNames();

//            puertoserial = (SerialPortList) puertos[cbBalanzaGrande.getSelectedIndex()];
//            puertoserial.setBa
            SerialPort[] sp = new SerialPort[cbBalanzaGrande.getSelectedIndex()];

        } catch (Exception e) {
        }


    }//GEN-LAST:event_btnOpenActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPortCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPortCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPortCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPortCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPortCom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbBalanzaChica;
    private javax.swing.JComboBox<String> cbBalanzaGrande;
    private javax.swing.JComboBox<String> cbBaudiosC;
    private javax.swing.JComboBox<String> cbBaudiosG;
    private javax.swing.JComboBox<String> cbDatosC;
    private javax.swing.JComboBox<String> cbDatosG;
    private javax.swing.JComboBox<String> cbParadaC;
    private javax.swing.JComboBox<String> cbParadaG;
    private javax.swing.JComboBox<String> cbParidadC;
    private javax.swing.JComboBox<String> cbParidadG;
    private javax.swing.JCheckBox chkBalanzaChica;
    private javax.swing.JCheckBox chkBalanzaGrande;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jpanel;
    // End of variables declaration//GEN-END:variables
}
