--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.567.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27/11/2021 12:39:02
-- Server version: 10.4.21
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Drop table `ticket_pesaje`
--
DROP TABLE IF EXISTS ticket_pesaje;

--
-- Drop table `tipodocumento`
--
DROP TABLE IF EXISTS tipodocumento;

--
-- Drop table `cliente`
--
DROP TABLE IF EXISTS cliente;

--
-- Drop table `persona`
--
DROP TABLE IF EXISTS persona;

--
-- Create table `persona`
--
CREATE TABLE persona (
  idpersona int(11) NOT NULL AUTO_INCREMENT,
  nombre1 varchar(45) DEFAULT NULL,
  nombre2 varchar(45) DEFAULT NULL,
  apaterno varchar(45) DEFAULT NULL,
  amaterno varchar(45) DEFAULT NULL,
  tipo_documento varchar(20) DEFAULT NULL,
  numdoc varchar(20) DEFAULT NULL,
  direccion varchar(100) DEFAULT NULL,
  telefono varchar(25) DEFAULT NULL,
  email varchar(50) DEFAULT NULL,
  PRIMARY KEY (idpersona)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `cliente`
--
CREATE TABLE cliente (
  idpersona int(11) NOT NULL,
  codigo_cliente varchar(255) DEFAULT NULL,
  PRIMARY KEY (idpersona)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE cliente
ADD CONSTRAINT FK_cliente_idpersona FOREIGN KEY (idpersona)
REFERENCES persona (idpersona) ON DELETE NO ACTION;

--
-- Create table `tipodocumento`
--
CREATE TABLE tipodocumento (
  idtipodoc int(11) NOT NULL AUTO_INCREMENT,
  nombredocumento varchar(45) DEFAULT NULL,
  PRIMARY KEY (idtipodoc)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `ticket_pesaje`
--
CREATE TABLE ticket_pesaje (
  idticketpesaje int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (idticketpesaje)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

-- 
-- Dumping data for table persona
--
-- Table sistemaalgodon.persona does not contain any data (it is empty)

-- 
-- Dumping data for table tipodocumento
--
INSERT INTO tipodocumento VALUES
(1, 'DNI'),
(2, 'RUC'),
(3, 'BREVETE');

-- 
-- Dumping data for table ticket_pesaje
--
-- Table sistemaalgodon.ticket_pesaje does not contain any data (it is empty)

-- 
-- Dumping data for table cliente
--
-- Table sistemaalgodon.cliente does not contain any data (it is empty)


-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;